#!/bin/bash

echo "Creating application symlinks..." 
# application specific configuration
ln -s i3/ $HOME/.config/i3
ln -s polybar/ $HOME/.config/polybar
ln -s dunst/ $HOME/.config/dunst
ln -s nitrogen/ $HOME/.config/nitrogen
ln -s x/ $HOME/.config/x
ln -s compton.conf $HOME/.config/compton.conf


echo "Creating general symlinks..."
# general configuration
ln -s .Xresources $HOME/.Xresources
ln -s .bashrc $HOME/.bashrc
ln -s .bash_profile $HOME./bash_profile

