#!/bin/bash

CONFIG_HOME="${HOME}/.config/"

echo "Creating application symlinks..."

# application specific configuration
ln -s $PWD/i3 $CONFIG_HOME
ln -s $PWD/polybar $CONFIG_HOME
ln -s $PWD/dunst $CONFIG_HOME
ln -s $PWD/nitrogen $CONFIG_HOME
ln -s $PWD/x $CONFIG_HOME
ln -s $PWD/compton/compton.conf $CONFIG_HOME
ln -s $PWD/tmux/.tmux.conf $HOME
ln -s $PWD/tmux/.tmux $HOME
ln -s $PWD/vim/.vimrc $HOME
ln -s $PWD/vim/.vim $HOME

echo "Creating general symlinks..."
# general configuration
ln -s $PWD/.Xresources $HOME
ln -s $PWD/.bashrc $HOME
ln -s $PWD/.bash_profile $HOME

